# 项目名称
spring:
  application:
    name: api-boot
  # 激活dev profile
  profiles:
    active: dev,memory
# Mybatis Enhance 相关配置
# 开源码云地址：https://gitee.com/hengboy/mybatis-enhance
hengboy:
  enhance:
    # 配置mybatis-enhance扫描自定义xml的位置
    mapper-locations: classpath:/mappers/*.xml
